stages:
  main:
    cmd: python3 main.py
    deps:
    - data/test.tsv
    - data/text_prepare_tests.tsv
    - data/train.tsv
    - data/validation.tsv
    - main.py
    - src/analysis.py
    - src/evaluation.py
    - src/multilabel.py
    - src/preprocessing.py
    - src/transform_text_to_vector.py
