stages:
  main:
    cmd: python main.py
    deps:
    - data/test.tsv
    - data/text_prepare_tests.tsv
    - data/train.tsv
    - data/validation.tsv
    - main.py
    - src/analysis.py
    - src/evaluation.py
    - src/multilabel.py
    - src/preprocessing.py
    - src/transform_text_to_vector.py
    metrics:
    - reports/bag-of-words-metrics.json:
        cache: false
    - reports/tfidf-metrics.json:
        cache: false
  validation:
    cmd: python src/data_validation.py
    deps:
    - data/test.tsv
    - data/text_prepare_tests.tsv
    - data/train.tsv
    - data/validation.tsv
    - src/data_validation.py
    outs:
    - reports/anomalies.md:
        cache: false
    - reports/stats.html:
        cache: false
    - reports/stats.txt:
        cache: false
  robustness:
    cmd: python src/robustness_evaluation.py
    deps:
    - data/test.tsv
    - data/text_prepare_tests.tsv
    - data/train.tsv
    - data/validation.tsv
    - src/preprocessing.py
    - src/multilabel.py
    - src/transform_text_to_vector.py
    - src/robustness_evaluation.py
    metrics:
    - reports/bag-of-words-robustness-metrics.json:
        cache: false
    - reports/tfidf-robustness-metrics.json:
        cache: false
